name: WakaTime Dev Metrics

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias à meia-noite UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Atualizar README com métricas do WakaTime
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_EDITORS: "true"
          SHOW_PROJECTS: "false"
          SHOW_OS: "true"
          SHOW_DAYS_OF_WEEK: "false"
          SHOW_LOC_CHART: "false"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_UPDATED_DATE: "false"
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_SHORT_INFO: "false"
          SHOW_COMMIT: "false"
          SHOW_LANGUAGE_PER_REPO: "false"


