name: Atualizar WakaTime no README

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"  # Atualiza a cada 2 horas

jobs:
  update-readme:
    name: Atualizar README com WakaTime
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

