name: WakaTime Dev Metrics

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias à meia-noite UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Atualizar README com métricas do WakaTime
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_EDITORS: "true"
          SHOW_PROJECTS: "true"
          SHOW_OS: "true"
          SHOW_TIMEZONE: "true"
          SECTION_NAME: "waka"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          COMMIT_MESSAGE: "Updated WakaTime dev metrics"
          LOCALE: "en"
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
